insert into tb_team (name, acronym, group_id, flag_url) values ('Catar', 'QAT', 1, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/bh.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Equador', 'ECU', 1, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/ec.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Holanda', 'NED', 1, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/nl.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Senegal', 'SEN', 1, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/sn.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Estados Unidos', 'USA', 2, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/us.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Inglaterra', 'ENG', 2, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/gb-eng.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Irã', 'IRN', 2, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/ir.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('País de Gales', 'WAL', 2, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/gb-wls.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Argentina', 'ARG', 3, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/ar.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Arábia Saudita', 'KSA', 3, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/sa.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('México', 'MEX', 3, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/mx.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Polônia', 'POL', 3, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/pl.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Austrália', 'AUS', 4, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/au.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Dinamarca', 'DEN', 4, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/dk.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('França', 'FRA', 4, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/fr.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Tunísia', 'TUN', 4, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/tn.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Alemanha', 'GER', 5, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/de.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Costa Rica', 'CRC', 5, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/cr.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Espanha', 'ESP', 5, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/es.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Japão', 'JPN', 5, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/jp.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Bélgica', 'BEL', 6, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/be.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Canadá', 'CAN', 6, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/ca.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Croácia', 'CRO', 6, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/hr.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Marrocos', 'MAR', 6, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/ma.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Brasil', 'BRA', 7, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/br.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Camarões', 'CMR', 7, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/cm.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Suíça', 'SUI', 7, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/ch.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Sérvia', 'SRB', 7, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/rs.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Coréia do Sul', 'KOR', 8, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/kr.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Gana', 'GHA', 8, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/gh.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Portugal', 'POR', 8, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/pt.webp');
insert into tb_team (name, acronym, group_id, flag_url) values ('Uruguai', 'URU', 8, 'https://world-cup-flags.s3.sa-east-1.amazonaws.com/flags/uy.webp');